[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "proakt"
version = "0.1.0"
readme = "README.md"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
py-modules = ["constants"]

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]
